//
// Created by maciek on 23.04.19.
//

#ifndef THEORY_AND_METHODS_OF_OPTIMIZATION_SOLVERWRAPPER_HPP
#define THEORY_AND_METHODS_OF_OPTIMIZATION_SOLVERWRAPPER_HPP

class SolverWrapper
{

};

#endif //THEORY_AND_METHODS_OF_OPTIMIZATION_SOLVERWRAPPER_HPP
